### ISSUE TITLE
docker-ce-23.0.x, docker-ce-rootless-extras-23.0.x - rpm circular dependency reference

### ISSUE THREAD

**Issue by devqaio** [docker/docker-ce-packaging#915] opened 2023-04-18 06:23 UTC
I am installing docker engine from rpm packages. I have downloaded the package from the link mentioned in [docker doc](https://docs.docker.com/engine/install/centos/).

While installing docker-ce, it is looking for docker-ce-rootless-extras and vice versa, creating a circular reference. I am facing this for all versions 23.0.x.
![image](https://user-images.githubusercontent.com/10003447/232688822-10107aa9-f9c2-4d16-9c13-cae0f1696db0.png)

![image](https://user-images.githubusercontent.com/10003447/232689159-417e898b-1cf9-4f67-8861-a12829479ae9.png)

Can someone help me understand, if I am missing something here?

**Comment by neersighted** [comment] 2023-06-30 15:48
You need to install all the packages in a single `yum` invocation -- `yum` can't solve the circular dependency unless all the packages are available to it.

**Comment by neersighted** [comment] 2023-09-20 17:32
Closing this for now as resolved.

**Closed as completed by neersighted** 2023-09-20 17:32 UTC

**Comment by thaJeztah** [comment] 2023-09-20 17:42
@neersighted wondering if we should make it "recommends" versus "requires", based on what's supported by the yum version; RHEL/CentOS 7 only supports "requires", but newer versions do support recommends. This is what we did for this other dependencies, such as compose; https://github.com/docker/docker-ce-packaging/blob/master/rpm/SPECS/docker-ce-cli.spec#L23

**Comment by neersighted** [comment] 2023-09-20 17:49
We could make it conditional on a macro, yeah. Would you mind opening an issue for that?

**Comment by thaJeztah** [comment] 2023-09-20 19:44
@neersighted a PR was faster than to describe it :joy https://github.com/docker/docker-ce-packaging/pull/945

**Comment by dberardo-com** [comment] 2024-06-17 12:28
i am trying to install docker in an airgap environment. how to solve this circular dependencies problem there? 

i am downloading all .rpm packages and installing them in a loop on the remote air gapped machine.

**Comment by thaJeztah** [comment] 2024-06-17 12:31
This probably won't work if you install them individually (in a loop); as mentioned above, you'd have to install all the related packages in a single invocation.

**Comment by dberardo-com** [comment] 2024-06-17 12:34
i have managed to install the docker-ce first with rmp -i --nodeps and then docker-ce-rootless without nodeps ... semes to hav eworked but cannot reproduce entirely :D

**Comment by dberardo-com** [comment] 2024-06-17 12:40
> you'd have to install all the related packages in a single invocation.

how to do that "offline" ?

**Comment by thaJeztah** [comment] 2024-06-17 12:42
See https://docs.docker.com/engine/install/ubuntu/#install-from-a-package

```bash
sudo dpkg -i <package 1> <package 2> <package 3> .....
```

**Comment by dberardo-com** [comment] 2024-06-17 13:43
i will try that with rpm -i instead

**Comment by dberardo-com** [comment] 2024-06-17 14:51
no chance that this can also happen with rpm ? my centos nodes have no dpkg
